apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-githubreleasesmonitor-viewer-role
  labels:
  {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - monitor.my.domain
  resources:
  - githubreleasesmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.my.domain
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get